name: Wheels

on:
  pull_request:
    branches:
      - master
  release:
    types: [published]

concurrency:
  group: wheels-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os:
          - windows-2019
          - ubuntu-22.04
          - macos-13
          - macos-14
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Normalize the path for the binder build directory
        id: path
        uses: mad9000/actions-find-and-replace-string@5
        with:
            source: ${{ github.workspace }}
            find: '\\'
            replace: '/'

      - name: Build the binder executable
        shell: bash
        run: |
          cmake ${{ env.CMAKE_OPTIONS }} -S . -B cmake-build
          cmake --build cmake-build --config Release --target binder
          pip wheel --wheel-dir dist .
        env:
          CMAKE_OPTIONS: >
            -DCMAKE_BUILD_TYPE=Release
            -DLLVM_ENABLE_EH=ON
            -DLLVM_ENABLE_RTTI=ON
            -DLLVM_ENABLE_PROJECTS=clang
            -DBINDER_BUILD_DIR=${{ steps.path.outputs.value }}/binder/bin

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl

      - name: Upload wheels to release
        if: github.event_name == 'release'
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} ./dist/*.whl --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-22.04
    steps:
      - name: Download wheels
        run: |
          gh release download ${{ github.ref_name }} --pattern *.whl --dir dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
