name: Wheels

on:
  pull_request:
    branches:
      - master
  release:
    types: [published]

concurrency:
  group: wheels-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os:
          - windows-2019
          - ubuntu-22.04
          - macos-13
          - macos-14
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build the binder executable
        shell: bash
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_PROJECTS=clang -DBINDER_BUILD_DIR=${GITHUB_WORKSPACE}/binder/bin -S . -B cmake-build
          cmake --build cmake-build --config Release --target binder

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env:
          CIBW_ARCHS: auto64
          CIBW_BUILD: cp312-*

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      - name: Upload wheels to release
        if: github.event_name == 'release'
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} ./wheelhouse/*.whl --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-22.04
    steps:
      - name: Download wheels
        run: |
          gh release download ${{ github.ref_name }} --pattern *.whl --dir wheelhouse
      - name: Publish package to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: wheelhouse
