name: Wheels

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/wheels.yml"
  release:
    types: [published]

concurrency:
  group: wheels-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os:
          - windows-2022
          - ubuntu-22.04
          - macos-13
          - macos-14
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1

      - uses: actions/upload-artifact@v4
        with:
          name: cppbinder-${{ matrix.os }}
          path: ./wheelhouse/*.whl

      - name: Upload wheels to release
        if: github.event_name == 'release'
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} ./wheelhouse/*.whl --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Download wheels
        run: |
          gh release download ${{ github.ref_name }} --pattern *.whl --dir wheelhouse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: wheelhouse
